### ISSUE TITLE
运行时的一些错误，希望帮助解答

### ISSUE THREAD

**Issue by chu888chu888** [Shu-Ji/WebpyAdmin#1]
我在运行你的程序的时候，出现了一些错误。我看了一下代码，您现在的代码基本上就是README需要修改的最新代码，所以我没有修改直接运行。但是出现了错误。希望能帮助解答修正一下，谢谢。
好像是缺少了webhelpers.html这个模板的原因。见下图。
![](http://tenyear-public.stor.sinaapp.com/tmp/20130414201534.png)
还有您是否可以留个联系方式，沟通也方便 哪。我找了一圈没有email.

**Comment by Shu-Ji** [comment]
是的，后来由于时间关系没有继续下去了，我想后面我会继续这个项目的[呵呵：2016-12-02]。

直接运行是可以的，但是不应该是从index_wsgi.py运行，这个文件在这里是没什么用的，你可以通过如下启动调试用服务器:

```
$ python start_server.py -p 8888
```

看截图是你的少了webhelpers模块，那可能其他模块你也没有，你可以按照如下罗列的模块都安装一下:

```
$ sudo pip install webhelpers tempita webob
```

留个邮箱吧:  `××××`
